@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account

POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "NOVOUSUARIO",
    "email": "novo.usuario@gmail.com",
    "password": "123"
}

### 

# @name authenticate

POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "novo.usuario@gmail.com",
    "password": "123"
}

### 

# @name create question

POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "email": "novo.usuario@gmail.com",
    "password": "123"
}